- alias: "Wake me up with bedroom light transition"
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.alarm_on
      state: 'on'
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
  action:
    - service: light.turn_on
      entity_id: group.light
      data:
              #transition: 60
        brightness: 1
        rgb_color: [1,0,0]
    - service: switch.turn_on
      entity_id: switch.flux

- alias: Turn lights ON if currently OFF
  trigger:
    platform: mqtt
    topic: home/button/toggle
  condition:
    condition: state
    entity_id: group.all_lights
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.all_lights

- alias: Turn lights OFF if currently ON
  trigger:
    platform: mqtt
    topic: home/button/toggle
  condition:
    condition: state
    entity_id: group.all_lights
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
