- alias: Xbox on routine
  hide_entity: true
  initial_state: true
  trigger: 
    platform: state
    entity_id: switch.xbox
    to: 'on'
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac
    - service: media_player.select_source
      entity_id: media_player.living_room_tv
      data:
        source: HDMI2
