- alias: Xbox on routine
  hide_entity: true
  initial_state: true
  trigger: 
    platform: state
    entity_id: switch.xbox
    to: 'on'
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac
    - service: media_player.select_source
      entity_id: media_player.tv
      data:
        source: HDMI2
- alias: playstation off when everything off
  initial_state: true
  trigger: 
    platform: state
    entity_id: group.everything
    to: 'off'
  action:
    - service: media_player.turn_off
      entity_id: media_player.playstation_4
- alias: Speakers on routine
  hide_entity: true
  initial_state: true
  trigger: 
    platform: state
    entity_id: switch.speakers
    to: 'on'
  action:
    - delay:
        seconds: 2
    - &volume_up
      service: homeassistant.turn_on
      entity_id: switch.volume
    - &ir_interval
      delay:
        milliseconds: 100
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
    - <<: *volume_up
    - <<: *ir_interval
