homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enable hass cloud for alexa
cloud:

logger:
  default: debug

system_log:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt:
  broker: localhost
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: yr
  - platform: mqtt
    state_topic: "home/living_room/window/battery"
    name: 'Living Room Window Battery'
    unit_of_measurement: 'V'
  - platform: mqtt
    name: "Bedroom Heating Energy"
    state_topic: "tele/sonoff1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Bedroom Heating Power"
    state_topic: "tele/sonoff1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Bedroom Heating Voltage"
    state_topic: "tele/sonoff1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Bedroom Heating Current"
    state_topic: "tele/sonoff1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"
  - platform: mqtt
    name: "Sonoff 2 Energy"
    state_topic: "tele/sonoff2/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Sonoff 2 Power"
    state_topic: "tele/sonoff2/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Sonoff 2 Voltage"
    state_topic: "tele/sonoff2/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Sonoff 2 Current"
    state_topic: "tele/sonoff2/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"
  - platform: mqtt
    name: "Living Room Heating Energy"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Living Room Heating Power"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Living Room Heating Voltage"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Living Room Heating Current"
    state_topic: "tele/sonoff3/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

binary_sensor:
  - platform: mqtt
    state_topic: 'home/living_room/window'
    name: 'Living Room Window'

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

light:
  - platform: yeelight
    devices:
      192.168.0.10:
        name: Light 1
        # transition: 1000
        # use_music_mode: True #(defaults to False)
        # save_on_change: false #(defaults to True)
      192.168.0.11:
        name: Light 2

ios:

switch:
  - platform: flux
    lights:
      - group.light
    transition: 3
    #  - platform: mqtt
    #    command_topic: 'home/button'
    #    state_topic: 'home/button'
    #    optimistic: true
    #    name: 'Button'
  - platform: mqtt
    name: "Bedroom Heating"
    state_topic: "stat/sonoff1/POWER"
    command_topic: "cmnd/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Sonoff2"
    state_topic: "stat/sonoff2/POWER"
    command_topic: "cmnd/sonoff2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Living Room Heating"
    state_topic: "stat/sonoff3/POWER"
    command_topic: "cmnd/sonoff3/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: true
  - platform: broadlink
    host: !secret ir_switch_ip
    mac: !secret ir_switch_mac
    friendly_name: 'IR Switch'
    switches:
      speakers:
        friendly_name: 'Speakers'
        command_on: 'JgBwAAABKZQTOBMSEhMTExI4EhQSExITEhQSOBI4EzgSExI5EzcSORITEjgSORI4EhQSExITEjkSOBIUEhMSExI5EjgSOBMTEgAFHAABKUoSAAxjAAEpShMADGEAASpKEwAMYQABKUoTAAxiAAEpShMADQUAAAAAAAAAAA=='
        command_off: 'JgBwAAABKZQTOBMSEhMTExI4EhQSExITEhQSOBI4EzgSExI5EzcSORITEjgSORI4EhQSExITEjkSOBIUEhMSExI5EjgSOBMTEgAFHAABKUoSAAxjAAEpShMADGEAASpKEwAMYQABKUoTAAxiAAEpShMADQUAAAAAAAAAAA=='
      volume:
        friendly_name: 'Speakers Volume'
        command_on: 'JgBQAAABKZQUNxQRFBIUERQ2FBIUERQRFBIUNhQ3FDYUEhQ2FDYVNhQ2FDcUNhM4ExITExITEjgTExMSEhMTExI4EzgTNxMSEwAFHAABKkoTAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABKJUSOBMTEhMSFBI4EhMTExITEhMTOBI4EzgSExI5FDYSORQ2EjkSExITEjkSExIUEjgSExIUEjgSORITEjgTOBITEgAFHQABKUoTAA0FAAAAAAAAAAA='
      xbox:
        friendly_name: 'Xbox'
        command_on: 'JgDGAFcdEA4PDg8cDxwtHBAODw4PDg8ODw4PDg8ODw4PDg8OHg4PDg8ODw4PDg8ODw4PHB4cEA4PDg8OHhweHB4cEAAI0FgdDw4PDg8dDxwtHA8ODw4PDg8ODw4PDg8OEA0QDg8OHQ4PDg8OEA0QDRAODw4PHB4cDw4QDRAOHRweHB4dDwAI0VcdEA0QDg8cDxwtHBANEA4PDg8ODw4PDg8ODw4PDg8OHg4PDg8ODw4PDg8ODw4PHB4cEA4PDg8OHhweHB4cEAANBQAA'
        command_off: 'JgDAAFceDRAPDg8cDx0sHBAODw4PDg8ODw4PDg8ODw4PDg8OHg4PDg0QDxweDg8ODx0dHQ8ODw4PDh0dHB4PDhwACOJXHQ4PDw4PHQ8cLRwQDQ4PDg8OEA4PDg8ODw4PDw4ODx0PDg8ODw4dHg4ODw4dHh0ODw4PDg8cHh0dDg8dAAjgWBwQDg8ODxwQHCwcEA4PDg8ODw4PDg8ODw4PDg8ODw4eDg8ODw4PHB4ODw4QHB4cDw4PDg8OHhweHBAOHQANBQAAAAAAAAAA'

wake_on_lan:

media_player:
  - platform: webostv
    host: !secret tv_ip
    name: Living Room TV
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret tv_mac
      - service: media_player.select_source
        data:
          source: HDMI1
  - platform: kodi
    host: !secret kodi_ip

scene:
  - name: Romantic
    entities:
      group.light:
        state: on
        transition: 3
        hs_color: [345, 100]
        brightness_pct: 50
  - name: Bright
    entities:
      group.light:
        state: on
        transition: 3
        color_temp: 184
        brightness_pct: 100
  - name: Yellow
    entities:
      group.light:
        state: on
        transition: 3
        color_temp: 325
        brightness_pct: 100

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token
